[2020-06-03 08:14:26,841] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: covid_dag.covid_data 2020-05-31T00:00:00+00:00 [queued]>
[2020-06-03 08:14:26,849] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: covid_dag.covid_data 2020-05-31T00:00:00+00:00 [queued]>
[2020-06-03 08:14:26,849] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 08:14:26,849] {taskinstance.py:867} INFO - Starting attempt 3 of 5
[2020-06-03 08:14:26,850] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 08:14:26,865] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): covid_data> on 2020-05-31T00:00:00+00:00
[2020-06-03 08:14:26,868] {standard_task_runner.py:53} INFO - Started process 29951 to run task
[2020-06-03 08:14:26,925] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_dag.covid_data 2020-05-31T00:00:00+00:00 [running]> nineleaps
[2020-06-03 08:14:27,575] {taskinstance.py:1128} ERROR - string indices must be integers
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python2.7/dist-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python2.7/dist-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/covid_data.py", line 69, in get_covid_data
    csv_writer.writerow([str(context['execution_date']).split('T')[0], i['State UT'], i[str(context['execution_date']).split('T')[0]]])
TypeError: string indices must be integers
[2020-06-03 08:14:27,577] {taskinstance.py:1151} INFO - Marking task as UP_FOR_RETRY
[2020-06-03 08:14:36,836] {logging_mixin.py:112} INFO - [2020-06-03 08:14:36,836] {local_task_job.py:103} INFO - Task exited with return code 1
[2020-06-03 08:18:52,573] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: covid_dag.covid_data 2020-05-31T00:00:00+00:00 [queued]>
[2020-06-03 08:18:52,581] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: covid_dag.covid_data 2020-05-31T00:00:00+00:00 [queued]>
[2020-06-03 08:18:52,581] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 08:18:52,581] {taskinstance.py:867} INFO - Starting attempt 3 of 3
[2020-06-03 08:18:52,581] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 08:18:52,597] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): covid_data> on 2020-05-31T00:00:00+00:00
[2020-06-03 08:18:52,600] {standard_task_runner.py:53} INFO - Started process 30569 to run task
[2020-06-03 08:18:52,672] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_dag.covid_data 2020-05-31T00:00:00+00:00 [running]> nineleaps
[2020-06-03 08:18:53,119] {taskinstance.py:1128} ERROR - string indices must be integers
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python2.7/dist-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python2.7/dist-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/covid_data.py", line 69, in get_covid_data
    csv_writer.writerow([context['execution_date'], i['State UT'], i[str(context['execution_date']).split('T')[0]]])
TypeError: string indices must be integers
[2020-06-03 08:18:53,122] {taskinstance.py:1170} INFO - All retries failed; marking task as FAILED.dag_id=covid_dag, task_id=covid_data, execution_date=20200531T000000, start_date=20200603T024852, end_date=20200603T024853
[2020-06-03 08:19:02,569] {logging_mixin.py:112} INFO - [2020-06-03 08:19:02,569] {local_task_job.py:103} INFO - Task exited with return code 1
