[2020-06-02 17:57:27,397] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: covid_dag_tra.covid_data 2020-05-31T00:00:00+00:00 [queued]>
[2020-06-02 17:57:27,405] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: covid_dag_tra.covid_data 2020-05-31T00:00:00+00:00 [queued]>
[2020-06-02 17:57:27,406] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-06-02 17:57:27,406] {taskinstance.py:867} INFO - Starting attempt 4 of 6
[2020-06-02 17:57:27,406] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-06-02 17:57:27,423] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): covid_data> on 2020-05-31T00:00:00+00:00
[2020-06-02 17:57:27,426] {standard_task_runner.py:53} INFO - Started process 5078 to run task
[2020-06-02 17:57:27,493] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_dag_tra.covid_data 2020-05-31T00:00:00+00:00 [running]> nineleaps
[2020-06-02 17:57:28,343] {logging_mixin.py:112} INFO - csv loaded successfully.
[2020-06-02 17:57:28,343] {taskinstance.py:1128} ERROR - 'execution-date'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python2.7/dist-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python2.7/dist-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/airflow_1.py", line 73, in get_covid_data
    print(context['execution-date'])
KeyError: 'execution-date'
[2020-06-02 17:57:28,345] {taskinstance.py:1151} INFO - Marking task as UP_FOR_RETRY
[2020-06-02 17:57:37,386] {logging_mixin.py:112} INFO - [2020-06-02 17:57:37,385] {local_task_job.py:103} INFO - Task exited with return code 1
